/**
 * Curated table of common commercially available restriction enzymes.
 *
 * Each entry is `[name, recognition site 5'→3' (IUPAC), cutTop, cutBottom]`
 * where the cut offsets count bases from the start of the site on the
 * forward strand: `cutTop` is where the top strand is cut, `cutBottom` where
 * the bottom strand is cut, both expressed in top-strand coordinates. So
 * EcoRI G^AATTC is `1, 5`; a blunt cutter has equal offsets; Type IIS
 * enzymes cut beyond the site, e.g. BsaI GGTCTC(1/5) is `7, 11`.
 *
 * Format is REBASE-compatible in spirit so a full REBASE import can replace
 * this table later (as docs/design/07-rebase-enzymes.md did). Entries were typed from
 * supplier catalogues; the unit tests check every palindromic entry for
 * cut-position symmetry.
 */
export const ENZYME_TABLE: readonly (readonly [string, string, number, number])[] = [
  ['AatII', 'GACGTC', 5, 1],
  ['AccI', 'GTMKAC', 2, 4],
  ['AclI', 'AACGTT', 2, 4],
  ['AfeI', 'AGCGCT', 3, 3],
  ['AflII', 'CTTAAG', 1, 5],
  ['AgeI', 'ACCGGT', 1, 5],
  ['AluI', 'AGCT', 2, 2],
  ['AlwNI', 'CAGNNNCTG', 6, 3],
  ['ApaI', 'GGGCCC', 5, 1],
  ['ApaLI', 'GTGCAC', 1, 5],
  ['AscI', 'GGCGCGCC', 2, 6],
  ['AseI', 'ATTAAT', 2, 4],
  ['AsiSI', 'GCGATCGC', 5, 3],
  ['AvaI', 'CYCGRG', 1, 5],
  ['AvrII', 'CCTAGG', 1, 5],
  ['BamHI', 'GGATCC', 1, 5],
  ['BbsI', 'GAAGAC', 8, 12],
  ['BbvI', 'GCAGC', 13, 17],
  ['BclI', 'TGATCA', 1, 5],
  ['BfuAI', 'ACCTGC', 10, 14],
  ['BglI', 'GCCNNNNNGGC', 7, 4],
  ['BglII', 'AGATCT', 1, 5],
  ['BlpI', 'GCTNAGC', 2, 5],
  ['BmtI', 'GCTAGC', 5, 1],
  ['BpmI', 'CTGGAG', 22, 20],
  ['BsaBI', 'GATNNNNATC', 5, 5],
  ['BsaHI', 'GRCGYC', 2, 4],
  ['BsaI', 'GGTCTC', 7, 11],
  ['BseRI', 'GAGGAG', 16, 14],
  ['BsgI', 'GTGCAG', 22, 20],
  ['BsiEI', 'CGRYCG', 4, 2],
  ['BsiWI', 'CGTACG', 1, 5],
  ['BsmBI', 'CGTCTC', 7, 11],
  ['BsmI', 'GAATGC', 7, 5],
  ['BspEI', 'TCCGGA', 1, 5],
  ['BspHI', 'TCATGA', 1, 5],
  ['BsrGI', 'TGTACA', 1, 5],
  ['BssHII', 'GCGCGC', 1, 5],
  ['BstAPI', 'GCANNNNNTGC', 7, 4],
  ['BstBI', 'TTCGAA', 2, 4],
  ['BstEII', 'GGTNACC', 1, 6],
  ['BstXI', 'CCANNNNNNTGG', 8, 4],
  ['BstZ17I', 'GTATAC', 3, 3],
  ['Bsu36I', 'CCTNAGG', 2, 5],
  ['BtgZI', 'GCGATG', 16, 20],
  ['BtsI', 'GCAGTG', 8, 6],
  ['ClaI', 'ATCGAT', 2, 4],
  ['DpnII', 'GATC', 0, 4],
  ['DraI', 'TTTAAA', 3, 3],
  ['DrdI', 'GACNNNNNNGTC', 7, 5],
  ['EagI', 'CGGCCG', 1, 5],
  ['EarI', 'CTCTTC', 7, 10],
  ['EcoNI', 'CCTNNNNNAGG', 5, 6],
  ['EcoO109I', 'RGGNCCY', 2, 5],
  ['EcoRI', 'GAATTC', 1, 5],
  ['EcoRV', 'GATATC', 3, 3],
  ['FokI', 'GGATG', 14, 18],
  ['FseI', 'GGCCGGCC', 6, 2],
  ['FspI', 'TGCGCA', 3, 3],
  ['HaeII', 'RGCGCY', 5, 1],
  ['HaeIII', 'GGCC', 2, 2],
  ['HgaI', 'GACGC', 10, 15],
  ['HincII', 'GTYRAC', 3, 3],
  ['HindIII', 'AAGCTT', 1, 5],
  ['HinfI', 'GANTC', 1, 4],
  ['HpaI', 'GTTAAC', 3, 3],
  ['HpaII', 'CCGG', 1, 3],
  ['HpyCH4V', 'TGCA', 2, 2],
  ['KasI', 'GGCGCC', 1, 5],
  ['KpnI', 'GGTACC', 5, 1],
  ['MboI', 'GATC', 0, 4],
  ['MfeI', 'CAATTG', 1, 5],
  ['MluI', 'ACGCGT', 1, 5],
  ['MlyI', 'GAGTC', 10, 10],
  ['MmeI', 'TCCRAC', 26, 24],
  ['MscI', 'TGGCCA', 3, 3],
  ['MseI', 'TTAA', 1, 3],
  ['MslI', 'CAYNNNNRTG', 5, 5],
  ['MspI', 'CCGG', 1, 3],
  ['NaeI', 'GCCGGC', 3, 3],
  ['NarI', 'GGCGCC', 2, 4],
  ['NcoI', 'CCATGG', 1, 5],
  ['NdeI', 'CATATG', 2, 4],
  ['NgoMIV', 'GCCGGC', 1, 5],
  ['NheI', 'GCTAGC', 1, 5],
  ['NlaIII', 'CATG', 4, 0],
  ['NotI', 'GCGGCCGC', 2, 6],
  ['NruI', 'TCGCGA', 3, 3],
  ['NsiI', 'ATGCAT', 5, 1],
  ['NspI', 'RCATGY', 5, 1],
  ['PacI', 'TTAATTAA', 5, 3],
  ['PciI', 'ACATGT', 1, 5],
  ['PflMI', 'CCANNNNNTGG', 7, 4],
  ['PleI', 'GAGTC', 9, 10],
  ['PmeI', 'GTTTAAAC', 4, 4],
  ['PmlI', 'CACGTG', 3, 3],
  ['PsiI', 'TTATAA', 3, 3],
  ['PspXI', 'VCTCGAGB', 2, 6],
  ['PstI', 'CTGCAG', 5, 1],
  ['PvuI', 'CGATCG', 4, 2],
  ['PvuII', 'CAGCTG', 3, 3],
  ['RsaI', 'GTAC', 2, 2],
  ['SacI', 'GAGCTC', 5, 1],
  ['SacII', 'CCGCGG', 4, 2],
  ['SalI', 'GTCGAC', 1, 5],
  ['SapI', 'GCTCTTC', 8, 11],
  ['Sau3AI', 'GATC', 0, 4],
  ['SbfI', 'CCTGCAGG', 6, 2],
  ['ScaI', 'AGTACT', 3, 3],
  ['SfaNI', 'GCATC', 10, 14],
  ['SfiI', 'GGCCNNNNNGGCC', 8, 5],
  ['SfoI', 'GGCGCC', 3, 3],
  ['SgrAI', 'CRCCGGYG', 2, 6],
  ['SmaI', 'CCCGGG', 3, 3],
  ['SnaBI', 'TACGTA', 3, 3],
  ['SpeI', 'ACTAGT', 1, 5],
  ['SphI', 'GCATGC', 5, 1],
  ['SrfI', 'GCCCGGGC', 4, 4],
  ['SspI', 'AATATT', 3, 3],
  ['StuI', 'AGGCCT', 3, 3],
  ['SwaI', 'ATTTAAAT', 4, 4],
  ['TaqI', 'TCGA', 1, 3],
  ['XbaI', 'TCTAGA', 1, 5],
  ['XhoI', 'CTCGAG', 1, 5],
  ['XmaI', 'CCCGGG', 1, 5],
  ['XmnI', 'GAANNNNTTC', 5, 5],
  ['ZraI', 'GACGTC', 3, 3],
];
