// Generated by scripts/make-genetic-codes.py from NCBI's genetic code table
// (version 4.6, https://ftp.ncbi.nlm.nih.gov/entrez/misc/data/gc.prt).
// Do not edit by hand: rerun the script instead.

/**
 * An NCBI genetic code, as it is written in a GenBank `/transl_table`
 * qualifier. Every code shares the same codon order, so the two strings are
 * read by position rather than by codon.
 */
export interface GeneticCode {
  readonly id: TranslationTable;
  /** NCBI's own name, e.g. "Vertebrate Mitochondrial". */
  readonly name: string;
  /**
   * One-letter amino acid per codon, `*` for a stop, in the codon order
   * TTT, TTC, TTA, TTG, TCT, … — that is, each base cycling T, C, A, G with
   * the third base fastest.
   */
  readonly aminoAcids: string;
  /** `M` where the codon may begin a coding sequence, `-` elsewhere; same order. */
  readonly starts: string;
}

/** The genetic codes we ship. NCBI's numbering has gaps: 7, 8 and 17–20 were withdrawn. */
export type TranslationTable =
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 9
  | 10
  | 11
  | 12
  | 13
  | 14
  | 15
  | 16
  | 21
  | 22
  | 23
  | 24
  | 25
  | 26
  | 27
  | 28
  | 29
  | 30
  | 31
  | 32
  | 33;

export const GENETIC_CODES: readonly GeneticCode[] = [
  {
    id: 1,
    name: 'Standard',
    aminoAcids: 'FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '---M------**--*----M---------------M----------------------------',
  },
  {
    id: 2,
    name: 'Vertebrate Mitochondrial',
    aminoAcids: 'FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSS**VVVVAAAADDEEGGGG',
    starts: '----------**--------------------MMMM----------**---M------------',
  },
  {
    id: 3,
    name: 'Yeast Mitochondrial',
    aminoAcids: 'FFLLSSSSYY**CCWWTTTTPPPPHHQQRRRRIIMMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '----------**----------------------MM---------------M------------',
  },
  {
    id: 4,
    name: 'Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma',
    aminoAcids: 'FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '--MM------**-------M------------MMMM---------------M------------',
  },
  {
    id: 5,
    name: 'Invertebrate Mitochondrial',
    aminoAcids: 'FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG',
    starts: '---M------**--------------------MMMM---------------M------------',
  },
  {
    id: 6,
    name: 'Ciliate Nuclear; Dasycladacean Nuclear; Hexamita Nuclear',
    aminoAcids: 'FFLLSSSSYYQQCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '--------------*--------------------M----------------------------',
  },
  {
    id: 9,
    name: 'Echinoderm Mitochondrial; Flatworm Mitochondrial',
    aminoAcids: 'FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNNKSSSSVVVVAAAADDEEGGGG',
    starts: '----------**-----------------------M---------------M------------',
  },
  {
    id: 10,
    name: 'Euplotid Nuclear',
    aminoAcids: 'FFLLSSSSYY**CCCWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '----------**-----------------------M----------------------------',
  },
  {
    id: 11,
    name: 'Bacterial, Archaeal and Plant Plastid',
    aminoAcids: 'FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '---M------**--*----M------------MMMM---------------M------------',
  },
  {
    id: 12,
    name: 'Alternative Yeast Nuclear',
    aminoAcids: 'FFLLSSSSYY**CC*WLLLSPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '----------**--*----M---------------M----------------------------',
  },
  {
    id: 13,
    name: 'Ascidian Mitochondrial',
    aminoAcids: 'FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSGGVVVVAAAADDEEGGGG',
    starts: '---M------**----------------------MM---------------M------------',
  },
  {
    id: 14,
    name: 'Alternative Flatworm Mitochondrial',
    aminoAcids: 'FFLLSSSSYYY*CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNNKSSSSVVVVAAAADDEEGGGG',
    starts: '-----------*-----------------------M----------------------------',
  },
  {
    id: 15,
    name: 'Blepharisma Macronuclear',
    aminoAcids: 'FFLLSSSSYY*QCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '----------*---*--------------------M----------------------------',
  },
  {
    id: 16,
    name: 'Chlorophycean Mitochondrial',
    aminoAcids: 'FFLLSSSSYY*LCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '----------*---*--------------------M----------------------------',
  },
  {
    id: 21,
    name: 'Trematode Mitochondrial',
    aminoAcids: 'FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNNKSSSSVVVVAAAADDEEGGGG',
    starts: '----------**-----------------------M---------------M------------',
  },
  {
    id: 22,
    name: 'Scenedesmus obliquus Mitochondrial',
    aminoAcids: 'FFLLSS*SYY*LCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '------*---*---*--------------------M----------------------------',
  },
  {
    id: 23,
    name: 'Thraustochytrium Mitochondrial',
    aminoAcids: 'FF*LSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '--*-------**--*-----------------M--M---------------M------------',
  },
  {
    id: 24,
    name: 'Rhabdopleuridae Mitochondrial',
    aminoAcids: 'FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSSKVVVVAAAADDEEGGGG',
    starts: '---M------**-------M---------------M---------------M------------',
  },
  {
    id: 25,
    name: 'Candidate Division SR1 and Gracilibacteria',
    aminoAcids: 'FFLLSSSSYY**CCGWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '---M------**-----------------------M---------------M------------',
  },
  {
    id: 26,
    name: 'Pachysolen tannophilus Nuclear',
    aminoAcids: 'FFLLSSSSYY**CC*WLLLAPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '----------**--*----M---------------M----------------------------',
  },
  {
    id: 27,
    name: 'Karyorelict Nuclear',
    aminoAcids: 'FFLLSSSSYYQQCCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '--------------*--------------------M----------------------------',
  },
  {
    id: 28,
    name: 'Condylostoma Nuclear',
    aminoAcids: 'FFLLSSSSYYQQCCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '----------**--*--------------------M----------------------------',
  },
  {
    id: 29,
    name: 'Mesodinium Nuclear',
    aminoAcids: 'FFLLSSSSYYYYCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '--------------*--------------------M----------------------------',
  },
  {
    id: 30,
    name: 'Peritrich Nuclear',
    aminoAcids: 'FFLLSSSSYYEECC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '--------------*--------------------M----------------------------',
  },
  {
    id: 31,
    name: 'Blastocrithidia Nuclear',
    aminoAcids: 'FFLLSSSSYYEECCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '----------**-----------------------M----------------------------',
  },
  {
    id: 32,
    name: 'Balanophoraceae Plastid',
    aminoAcids: 'FFLLSSSSYY*WCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG',
    starts: '---M------*---*----M------------MMMM---------------M------------',
  },
  {
    id: 33,
    name: 'Cephalodiscidae Mitochondrial',
    aminoAcids: 'FFLLSSSSYYY*CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSSKVVVVAAAADDEEGGGG',
    starts: '---M-------*-------M---------------M---------------M------------',
  },
];
