// Writes src/core/alignment/blosum62.ts from NCBI's published BLOSUM62.
//
//   node scripts/make-blosum.mjs            # fetch and write
//   node scripts/make-blosum.mjs --offline  # from the cache only
//
// The matrix is Henikoff & Henikoff's (1992), as distributed by the NCBI
// with BLAST; a US government work, free of copyright. It is fetched rather
// than typed so that the 576 numbers are the published ones — the same rule
// the feature database follows (item 59).

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = dirname(HERE);
const CACHE = join(HERE, 'feature-db', '.cache', 'BLOSUM62');
const OUT = join(ROOT, 'src', 'core', 'alignment', 'blosum62.ts');
const URL = 'https://ftp.ncbi.nlm.nih.gov/blast/matrices/BLOSUM62';

async function fetchMatrix() {
  if (existsSync(CACHE)) return readFileSync(CACHE, 'utf8');
  if (process.argv.includes('--offline')) throw new Error(`Not cached: ${CACHE}`);
  const res = await fetch(URL);
  if (!res.ok) throw new Error(`${URL}: HTTP ${res.status}`);
  const text = await res.text();
  mkdirSync(dirname(CACHE), { recursive: true });
  writeFileSync(CACHE, text);
  return text;
}

const text = await fetchMatrix();
const lines = text.split('\n').filter((l) => l.trim() !== '' && !l.startsWith('#'));
const header = (lines[0] ?? '').trim().split(/\s+/);
if (header.length < 20) throw new Error('BLOSUM62: no header row');
/** @type {number[][]} */
const rows = [];
/** @type {string[]} */
const letters = [];
for (const line of lines.slice(1)) {
  const [letter, ...values] = line.trim().split(/\s+/);
  if (letter === undefined) continue;
  const numbers = values.map(Number);
  if (numbers.length !== header.length || numbers.some((n) => !Number.isFinite(n))) {
    throw new Error(`BLOSUM62: row ${letter} has ${String(numbers.length)} values`);
  }
  letters.push(letter);
  rows.push(numbers);
}
if (letters.join('') !== header.join('')) throw new Error('BLOSUM62: rows and columns differ');

const width = 3;
const table = rows
  .map((row, i) => `  [${row.map((n) => String(n).padStart(width)).join(',')}], // ${letters[i]}`)
  .join('\n');

writeFileSync(
  OUT,
  `/**
 * BLOSUM62, the substitution matrix protein alignments are scored by
 * (Henikoff & Henikoff 1992, PNAS 89:10915), exactly as the NCBI
 * distributes it with BLAST: a US government work, free of copyright.
 *
 * Generated by \`scripts/make-blosum.mjs\`; do not edit. The numbers are
 * fetched rather than typed, so they are the published ones.
 */

/** Row and column order of the matrix, as the NCBI's file has them. */
export const BLOSUM62_ORDER = '${letters.join('')}';

// prettier-ignore
export const BLOSUM62: readonly (readonly number[])[] = [
${table}
];
`,
);
process.stdout.write(`Wrote ${letters.length}×${letters.length} BLOSUM62 to ${OUT}\n`);
