#!/usr/bin/env python3
"""Regenerates src/core/analysis/geneticCodes.ts from NCBI's genetic code table.

The source of truth is NCBI's own ASN.1 file, which carries every code as two
64-character strings in codon order TTT, TTC, TTA, TTG, TCT, ... — the amino
acid for each codon, and which codons may start a coding sequence. Typing
those by hand is how a translation table ends up quietly wrong, so they are
generated instead.

Usage:  python3 scripts/make-genetic-codes.py [path/to/gc.prt]
        With no argument the file is downloaded from
        https://ftp.ncbi.nlm.nih.gov/entrez/misc/data/gc.prt
"""
import re
import sys
import urllib.request

URL = 'https://ftp.ncbi.nlm.nih.gov/entrez/misc/data/gc.prt'
OUT = 'src/core/analysis/geneticCodes.ts'


def read_source() -> str:
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding='utf-8') as f:
            return f.read()
    with urllib.request.urlopen(URL, timeout=60) as r:
        return r.read().decode('utf-8')


def parse(text: str):
    version = re.search(r'--\s+Version\s+([\d.]+)', text)
    codes = []
    for record in re.findall(r'\{\s*(name\s+"[^}]*?)\s*\}', text, re.S):
        name = re.search(r'name\s+"([^"]*)"', record)
        ident = re.search(r'id\s+(\d+)', record)
        aas = re.search(r'ncbieaa\s+"([^"]*)"', record)
        starts = re.search(r'sncbieaa\s+"([^"]*)"', record)
        if not (name and ident and aas and starts):
            raise SystemExit(f'incomplete record: {record[:60]!r}')
        if len(aas.group(1)) != 64 or len(starts.group(1)) != 64:
            raise SystemExit(f'code {ident.group(1)} is not 64 codons long')
        codes.append({
            'id': int(ident.group(1)),
            # A name may be wrapped over two lines, and several codes list
            # more than one name; the first is the one NCBI leads with.
            'name': ' '.join(name.group(1).split()),
            'aas': aas.group(1),
            'starts': starts.group(1),
        })
    if not codes:
        raise SystemExit('no genetic codes found in the input')
    return version.group(1) if version else 'unknown', codes


def render(version: str, codes) -> str:
    # Written the way Prettier would (single quotes, one union member per
    # line at this width), so a regenerated file needs no reformatting.
    ids = '\n'.join(f"  | {c['id']}" for c in codes)
    entries = '\n'.join(
        "  {{\n"
        "    id: {id},\n"
        "    name: '{name}',\n"
        "    aminoAcids: '{aas}',\n"
        "    starts: '{starts}',\n"
        "  }},".format(**c)
        for c in codes
    )
    return f'''// Generated by scripts/make-genetic-codes.py from NCBI's genetic code table
// (version {version}, https://ftp.ncbi.nlm.nih.gov/entrez/misc/data/gc.prt).
// Do not edit by hand: rerun the script instead.

/**
 * An NCBI genetic code, as it is written in a GenBank `/transl_table`
 * qualifier. Every code shares the same codon order, so the two strings are
 * read by position rather than by codon.
 */
export interface GeneticCode {{
  readonly id: TranslationTable;
  /** NCBI's own name, e.g. "Vertebrate Mitochondrial". */
  readonly name: string;
  /**
   * One-letter amino acid per codon, `*` for a stop, in the codon order
   * TTT, TTC, TTA, TTG, TCT, … — that is, each base cycling T, C, A, G with
   * the third base fastest.
   */
  readonly aminoAcids: string;
  /** `M` where the codon may begin a coding sequence, `-` elsewhere; same order. */
  readonly starts: string;
}}

/** The genetic codes we ship. NCBI's numbering has gaps: 7, 8 and 17–20 were withdrawn. */
export type TranslationTable =
{ids};

export const GENETIC_CODES: readonly GeneticCode[] = [
{entries}
];
'''


def main() -> None:
    version, codes = parse(read_source())
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(render(version, codes))
    print(f'{OUT}: {len(codes)} genetic codes from NCBI version {version}')


if __name__ == '__main__':
    main()
